### ISSUE TITLE
Can you tell me how to use VA_RNN ? please

### ISSUE THREAD

**Issue by hsclyy** [jiamingNo1/VA_NN#1]
我成功运行了VA_CNN。但当我在默认参数中换成VA_RNN时，显示报错。我尝试把main.py中残差网络的部分去掉，然后再运行VA_RNN的模型，但显示“optimizer got an empty parameter ”。我找了很多种方法都不能运行VA_RNN。请您能够告诉我如何用最简单的方式来使用VA_RNN模型吗？非常感谢！

I successfully run VA_CNN. But when I change to VA_RNN in the default parameters, it shows an error. I tried removing the part of the residual network in main.py and then running the model of VA_RNN, but it showed "optimizer got an empty parameter". I have found many ways that I can't run VA_RNN. Could you please tell me how to use the VA_RNN model in the simplest way? thank you very much!

**Comment by jiamingNo1** [comment]
@hsclyy VA_RNN模型的初始化函数__init__写成了__int__，现在我已经将他们更改好了，可以运行，但是还没训练足够好，有问题可以继续交流讨论。

**Comment by hsclyy** [comment]
非常感谢你的帮助！
